Committing Bluetooth LE
Project won’t build due to issue with Progress HUD:

UI/Screens/Scanner/Home/ScannerHome.cs(17,3): error CS0012: The type
`MonoTouch.UIKit.UIView' is defined in an assembly that is not
referenced. Consider adding a reference to assembly `monotouch,
Version=0.0.0.0, Culture=neutral, PublicKeyToken=84e04ff9cfb79065'